# -*- coding: utf-8 -*-
"""
Created on Mon Nov 02 09:00:45 2015

@author: xz804
"""
from DataStruct import *

from ReadInp import ReadInp
# Read input file generated by Abaqus

from SolElasStatics import SolElasStatics
# Solve elastic static solid problem in 2D (plane stress + plane strain)

from SolFractureElasStatics import SolFractureElasStatics
# Solve Fracture problem using phase-field approach

#from WriteToGid import WriteToGid
# write results to files for post-processing software Gid